---
apiVersion: v1
kind: Service
metadata:
  name: catalogoproducto 
  labels:
    app: catalogoproducto
spec:
  type: NodePort
  selector:
    app: catalogoproducto
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: catalogoproducto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogoproducto
    spec:
      containers:
      - name: catalogoproducto
        image: scastell77/oficatalogoproducto:1.0
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
