---
apiVersion: v1
kind: Service
metadata:
  name: comprafront
  labels:
    app: comprafront
spec:
  type: NodePort
  selector:
    app: comprafront
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: comprafront
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: comprafront
    spec:
      containers:
      - name: comprafront
        image: scastell77/oficomprafront:1.0
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
