---
apiVersion: v1
kind: Service
metadata:
  name: gestionstock
  labels:
    app: gestionstock
spec:
  type: NodePort
  selector:
    app: gestionstock
  ports:
  - protocol: TCP
    port: 8030
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gestionstock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gestionstock
    spec:
      containers:
      - name: gestionstock
        image: scastell77/ofigestionstock:1.0
        ports:
        - containerPort: 8030
        livenessProbe:
          httpGet:
            path: /health
            port: 8030
          initialDelaySeconds: 30
          timeoutSeconds: 1
